- hosts: localhost
  connection: local
  vars:
    controller_labels:
      Custom:
        natural_key:
          name: Custom
          organization:
            name: Default
            type: organization
          type: label
  tasks:
    - name: Export all assets
      ansible.controller.export:
        all: True
        controller_host: "{{ host }}"
        controller_username: "{{ user }}"
        controller_password: "{{ pass }}"
      register: export_output
    - name: print
      ansible.builtin.debug:
        msg: "{{ export_output }}"