- hosts: localhost
  gather_facts: no
  tasks:
    - name: Obtain SSO token
      ovirt.ovirt.ovirt_auth:
        url: "{{ api_url }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        insecure: true
    - ovirt.ovirt.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name=test* and cluster=Default
      register: result
    - ansible.builtin.debug:
        msg: "{{ result.ovirt_vms[0].id }}"
    # Gather information about all clusters which names start with C<production>:
    - ovirt.ovirt.ovirt_cluster_info:
        auth: "{{ ovirt_auth }}"
        pattern: "name=Default*"
      register: cluster
    - ansible.builtin.debug:
        msg: "{{ cluster.ovirt_clusters }}"
    # Gather information about all data centers which names start with C(production):
    - ovirt.ovirt.ovirt_datacenter_info:
        auth: "{{ ovirt_auth }}"
        pattern: name=Default*
      register: dc
    - ansible.builtin.debug:
        msg: "{{ dc.ovirt_datacenters }}"
    # Gather information about all image external providers named C<glance>:
    - ovirt.ovirt.ovirt_external_provider_info:
        auth: "{{ ovirt_auth }}"
        type: os_network
      register: external
    - ansible.builtin.debug:
        msg: "{{ external.ovirt_external_providers }}"
    # Gather information about all VMs which relate to a storage domain and
    # are unregistered:
    - ovirt.ovirt.ovirt_storage_vm_info:
        auth: "{{ ovirt_auth }}"
      register: stor
    - ansible.builtin.debug:
        msg: "{{ stor.ovirt_storage_vms }}"




