- hosts: "{{ vm_name | default('all') }}"
  gather_facts: no
  become: no
  tasks:
    - name: Test reachability to 10.10.10.10 using default vrf
      ansible.netcommon.net_ping:
        dest: "{{ ansible_host }}"
      delegate_to: localhost
      when: "'windows' in os"