- hosts: "{{ vm_name | default('all') }}"
  gather_facts: no
  become: no
  tasks:
    - name: ping test
      ansible.builtin.shell: ping -c 1 -w 2 {{ ansible_host }}
      delegate_to: localhost
      when: "'windows' in os"