- hosts: "{{ vm_name | default('all') }}"
  gather_facts: no
  become: no
  tasks:
    - name: Collect IP Addresses
      ansible.builtin.set_stats:
        data:
          vm_ip_addr: "{{ vm_ip_addr | default([]) + [{'ip': hostvars[item]['ansible_host']}] }}"
      loop: "{{ ansible_play_hosts }}"
      run_once: true
      delegate_to: localhost
      when: "'windows' in os"

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      ansible.builtin.wait_for:
        port: 3389
        host: '{{ item.ip }}'
        delay: 10
      vars:
        ansible_connection: local
      loop: "{{ vm_ip_addr }}"