- hosts: "{{ group_name }}-new"
  gather_facts: no
  become: no
  tasks:
    - name: Wait host to become available
      ansible.builtin.wait_for:
        port: 3389
        host: '{{ item.ip }}'
        delay: 10
      vars:
        ansible_connection: local
      loop: "{{ vm_ip_addr }}"
    - name: print
      ansible.builtin.debug:
        msg: "{{ ansible_play_hosts }}"