- hosts: localhost
  connection: local
  vars:
    controller_labels:
      Custom:
        natural_key:
          name: Custom
          organization:
            name: Default
            type: organization
          type: label
  tasks:
    - name: import labels test
      ansible.controller.import:
        assets: "{{ controller_labels }}"
        controller_host: "{{ host }}"
        controller_username: "{{ user }}"
        controller_password: "{{ pass }}"

