- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
    timeout: "{{ pause_timer }}"

- name: "Check {{ group_name }} virtual machines availability after migration"
  ansible.builtin.include_tasks: "{{ group_name }}.yml"

- name: Obtain SSO token
  ovirt.ovirt.ovirt_auth:
    insecure: true

- name: Set comment
  ovirt.ovirt.ovirt_vm:
    auth: "{{ ovirt_auth }}"
    id: "{{ item.id }}"
    comment: "{{ message }}"
  loop: "{{ vm_ids }}"
