#- name: Wait for system to become reachable over WinRM
#  ansible.builtin.wait_for_connection:
#    timeout: 900
#  delegate_to: localhost
#
#- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
#  ansible.builtin.wait_for:
#    port: 22
#    host: '{{ ansible_host }}'
#    search_regex: OpenSSH
#    delay: 10
#  vars:
#    ansible_connection: local
#  loop: "{{ groups['all'] }}"
#  register: results

- name: Obtain SSO token
  ovirt.ovirt.ovirt_auth:
    insecure: true
- ovirt.ovirt.ovirt_vm:
    id: cef535ae-e977-4ed1-9178-f56807b3ca66
    comment: "migrated to OCP Virt"
