- name: Build unique name
  ansible.builtin.set_fact:
    plan_name: "{{ source }}-{{ dc_name | lower }}-{{ cluster_name | lower }}-{{ network_name }}-{{ (999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N'))) | to_uuid() }}"

- name: Deploy Virtualization Plan
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Plan
      metadata:
        name: "{{ plan_name }}"
        namespace: openshift-mtv
      spec:
        archived: false
        description: "Migrating VMs from {{ network_name }}"
        map:
          network:
            name: "{{ source }}-{{ network_name }}"
            namespace: openshift-mtv
          storage:
            name: "{{ source }}-{{ sorage_domain_name | lower }}"
            namespace: openshift-mtv
        provider:
          destination:
            name: host
            namespace: openshift-mtv
          source:
            name: "{{ source }}"
            namespace: openshift-mtv
        targetNamespace: "{{ target_ns }}"
        vms: "{{ vms_for_plan_spec }}"
        warm: false