- name: Obtain SSO token
  ovirt.ovirt.ovirt_auth:
    insecure: true

- name: print
  ansible.builtin.debug:
    msg: "{{ cluster_name[0] }}"

- name: Obtain VM Info
  ovirt.ovirt.ovirt_vm_info:
    auth: "{{ ovirt_auth }}"
    pattern: "cluster={{ cluster_name[0] }}"
  register: vm_info

- name: Obtain Cluster Info
  ovirt.ovirt.ovirt_cluster_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ cluster_name[0] }}"
  register: cluster_info

- name: Obtain Data Center Info
  ovirt.ovirt.ovirt_datacenter_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ dc_name }}"
  register: dc_info

- name: Obtain Storage Info
  ovirt.ovirt.ovirt_storage_domain_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ sorage_domain_name }} and datacenter={{ dc_name }}"
  register: storage_info

- name: Obtain Network Info
  ovirt.ovirt.ovirt_network_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ network_name }}"
  register: network_info

- name: Setting gathered Infra facts
  ansible.builtin.set_fact:
    dc_id: "{{ dc_info.ovirt_datacenters[0].id }}"
    cluster_id: "{{ cluster_info.ovirt_clusters[0].id }}"
    network_id: "{{ network_info.ovirt_networks[0].id }}"
    storage_id: "{{ storage_info.ovirt_storage_domains[0].id }}"

- name: Setting gathered VM facts
  ansible.builtin.set_fact:
    vms_for_plan_spec: "{{ vms_for_plan_spec | default([]) + [{'hooks': [], 'id': item.id, 'name': item.name }] }}"
  loop: "{{ vm_info.ovirt_vms }}"
  when: item.name in vm_name



#- name: Setting gathered facts
#  ansible.builtin.set_fact:
#    dc_id: "{{ dc_info.ovirt_datacenters[0].id }}"
#    cluster_id: "{{ cluster_info.ovirt_clusters[0].id }}"
#    network_id: "{{ network_info.ovirt_networks[0].id }}"
#    storage_id: "{{ storage_info.ovirt_storage_domains[0].id }}"
#    vm_id: "{{ vm_info.ovirt_vms[0].id }}"
#    vms_for_plan_spec: "{{ vms_for_plan_spec | default([]) + [{'hooks': [], 'id': vm_info.ovirt_vms[0].id, 'name': vm_name }] }}"
#
- name: Collect Global VM IDs
  ansible.builtin.set_stats:
    data:
      vm_ids: "{{ vms_for_plan_spec }}"