- name: Create a Migration manifest to run the Plan
  redhat.openshift.k8s:
    wait: true
    api_version: forklift.konveyor.io/v1beta1
    kind: Migration
    namespace: openshift-mtv
    name: "{{ plan_name }}"
    definition:
      metadata:
        name: "{{ plan_name }}"
        namespace: openshift-mtv
      spec:
        plan:
          name: "{{ plan_name }}"
          namespace: openshift-mtv

- name: Wait for stabilization
  ansible.builtin.wait_for_connection:
    timeout: 300