- name: Create a Migration manifest to run the Plan
  redhat.openshift.k8s:
    wait: true
    api_version: forklift.konveyor.io/v1beta1
    kind: Migration
    namespace: openshift-mtv
    name: "{{ plan_name }}"
    definition:
      metadata:
        name: "{{ plan_name }}"
        namespace: openshift-mtv
      spec:
        plan:
          name: "{{ plan_name }}"
          namespace: openshift-mtv

- name: Wait for virtual machines migration task succeed
  kubernetes.core.k8s_info:
    name: "{{ plan_name }}"
    namespace: openshift-mtv
    kind: Plan
    api_version: "forklift.konveyor.io/v1beta1"
  register: migrate_status
  until: migrate_status|json_query('resources[*].status.conditions[0].message')|unique == ["The plan execution has SUCCEEDED."]
  retries: "{{ migrate_default_retry }}"
  delay: "{{ migrate_default_delay }}"

- name: Virtual machines migrated
  ansible.builtin.debug:
    msg: "{{ migrate_status|json_query('resources[*].status.conditions[0].message')|unique }}"

